TRUNCATE TABLE personal_data RESTART IDENTITY CASCADE;
TRUNCATE TABLE cards RESTART IDENTITY CASCADE;
TRUNCATE TABLE sku_groups RESTART IDENTITY CASCADE;
TRUNCATE TABLE sku RESTART IDENTITY CASCADE;
TRUNCATE TABLE stores RESTART IDENTITY CASCADE;
TRUNCATE TABLE transactions RESTART IDENTITY CASCADE;
TRUNCATE TABLE checks RESTART IDENTITY CASCADE;

DELETE FROM databasechangelog WHERE filename LIKE '%/v-2.0-import/%';
DROP TABLE databasechangelog;
CALL set_margin_type('default');